version: "3.9"
services:
  proxy:
    image: traefik:v2.6
    ports:
      - "80:80"
    networks:
      - default
    environment:
      - TZ=Europe/Budapest
    volumes:
      - ./proxy/traefik.yaml:/traefik/config.yaml
    command:
      - --providers.file.directory=/traefik/
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.bufferingsize=100
      - --accesslog.filters.statuscodes=399-560
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.names.Authorization=drop
      - --log.format=json
      - --log.level=WARNING
      - --entrypoints.web.address=:80
      - --ping=true
      - --ping.entryPoint=web
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.entryPoint=web

  php-api:
    image: kajapp-php-api
    container_name: "kajapp-php-api"
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://admin:SuperSecret99@database:5432/postgres?charset=utf8"
      JWT_PASSPHRASE: "randomSecureText"
    networks:
      - default

  client:
    image: kajapp-client
    container_name: "kajapp-client"
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client/.output:/srv
    networks:
      - default

  client-builder:
    image: kajapp-client-builder
    container_name: "kajapp-client-builder"
    user: 1000:1000
    build:
      context: hack
      dockerfile: npm-builder.dockerfile
    volumes:
      - ./client:/app
    command:
      - find . -type f -not -path "*/.nuxt/*" -not -path "*/node_modules/*" -not -path "*/.output/*" -print | entr npm run generate --loglevel error

  database:
    image: postgres:13.6-alpine3.15
    container_name: "kajapp-database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "SuperSecret99"
    networks:
      - default