lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    # key under which the user identity will be stored in the token payload
    user_identity_field: email
    encoder:
        signature_algorithm: HS512
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        # check token in a cookie
        cookie:
            enabled: false
            name: BEARER
        # check token in query string parameter
        query_parameter:
            enabled: false
            name: bearer
